#!/bin/bash

echo Deleting old build directory
rm -rf build
rm -rf CMakeCache.txt CMakeFiles
echo Creating new build directory
mkdir build
cd build
echo Configuring....
export HDF5_ROOT=/usr/local/hdf5
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/cheetah -DCBF_INCLUDE_DIR=/usr/include/cbf ..
echo ""
echo ""
read -p "Finished. Press any key to open ccmake and double ceck all settings. Remember to set CMAKE_INSTALLATION_PREFIX to the install directory " -n1 -s
echo ""
echo ""
echo "********** IMPORTANT ************"
echo Done, now change into the build directory, then type make and make install
echo "**********************************"
